### ISSUE TITLE
Make the code easier to compile and run

### ISSUE THREAD

**Issue by defeo** [defeo/ffisom#22]
The referee examined the source code provided.

The referee very much encourage the authors' initiative to publish
the source code used for the paper. 

Unfortunately there is no documentation how it should be used, and
there are no clear licensing condition, no documentation how the
software should be build and what software are required to be installed
before the build (quite a lot apparently). 
As a result the source code was close to useless to the referee.

After lots of trial and errors, the referee managed to build something.
However one of the test did not compile with g++ 7.2.0

```
$ cd ffisom/implementation/kummer_c++_flint/test
$ make
g++ -o test_poly_eval test_poly_eval.cpp -Wall -O3 -g -I.. -L.. -lkummer
-lflint -lmpfr -lgmp
test_poly_eval.cpp: In function 'void test_eval(mp_limb_signed_t,
mp_limb_signed_t)':
test_poly_eval.cpp:40:69: error: no matching function for call to
'fq_nmodPolyEval::multipoint_eval(nmod_poly_struct (*&)[1],
fq_nmod_poly_t, nmod_poly_struct (*&)[1], mp_limb_signed_t&,
fq_nmod_ctx_t)'
 fq_nmodPolyEval.multipoint_eval(results, g, points, num_points, ctx);
                                                                    ^
In file included from test_poly_eval.cpp:2:0:
../fq_nmod_poly_eval.h:37:10: note: candidate: void
fq_nmodPolyEval::multipoint_eval(fq_nmod_struct*, const
fq_nmod_poly_struct*, const fq_nmod_struct*, mp_limb_signed_t, const
fq_nmod_ctx_struct*)
    void multipoint_eval(fq_nmod_struct *results, const fq_nmod_poly_t
f, const fq_nmod_struct *points, slong num_points, const fq_nmod_ctx_t
ctx);
         ^~~~~~~~~~~~~~~
../fq_nmod_poly_eval.h:37:10: note:   no known conversion for argument 1
from 'nmod_poly_struct (*)[1]' to 'fq_nmod_struct* {aka
nmod_poly_struct*}'
Makefile:17: recipe for target 'test_poly_eval' failed
make: *** [test_poly_eval] Error 1
```

**Comment by defeo** [comment]
We could (finally!) use mybinder to make it easier for the reviewer:
https://groups.google.com/forum/#!topic/sage-devel/dpnGrr78v7I
